"""update user and ride models

Revision ID: 2959c5e3f9b0
Revises: c9cfdf7c34de
Create Date: 2026-05-16 11:42:44.349884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2959c5e3f9b0'
down_revision: Union[str, Sequence[str], None] = 'c9cfdf7c34de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('fare', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('rides', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('rides', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('rides', 'rider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rides', 'pickup',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rides', 'dropoff',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'rides', 'users', ['driver_id'], ['id'])
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'is_online')
    op.drop_column('users', 'phone')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.alter_column('rides', 'dropoff',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rides', 'pickup',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rides', 'rider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('rides', 'updated_at')
    op.drop_column('rides', 'created_at')
    op.drop_column('rides', 'otp')
    op.drop_column('rides', 'distance_km')
    op.drop_column('rides', 'fare')
    # ### end Alembic commands ###
